gg.jte.usePrecompiledTemplates=true
#gg.jte.development-mode=true
spring.application.name=kotlinftw
spring.threads.virtual.enabled=true
spring.datasource.password=secret
spring.datasource.username=myuser
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase